### ISSUE TITLE
Use tags to make this project searchable on Github

### ISSUE THREAD

**Issue by green-coder** [EbTech/rust-algorithms#1]
It would be cool is this project was properly tagged, to be searchable on Github (for example, using `rust`, `algorithm`, etc ...). Tags are located  under the name of the project.

**Comment by EbTech** [comment]
I guess you mean the "topics"? I just added some, thanks.

**Comment by green-coder** [comment]
Yes, that's what I meant. I suggest to add the `learn` or `education` topic somewhere in the list.
