### ISSUE TITLE
Reading lots of integers

### ISSUE THREAD

**Issue by koutoftimer** [EbTech/rust-algorithms#11]
Reading 2e5 integers from the file.

Your solution with unsafe gives times:
```
> cargo run
0.380072
> cargo run
0.328795
> cargo run
0.320145
```
Handmade parser over byte stream:
```
> cargo run
0.14436
> cargo run
0.130388
> cargo run
0.13056
```

<details>
<summary>code with test case attached</summary>

```rust
use std::fs;
use std::io::{self, prelude::*};
use std::time::Instant;
use std::error::Error;

struct Parser
{
	it: std::vec::IntoIter<u8>,
}

impl Parser
{
	fn new(bytes: Vec<u8>) -> Parser {
		Parser { it: bytes.into_iter() }
	}
}

impl Iterator for Parser {
	type Item = i32;

	fn next(&mut self) -> Option<Self::Item> {
		let mut ans = 0;
		let mut sign = 1;
		let mut started = false;
		
		while let Some(b) = self.it.next() {
			if b >= b'0' && b <= b'9' {
				started = true;
				ans = (b - b'0') as i32 + ans * 10;
			} else if b == b'-' {
				sign = -1;
			} else if started == true {
				break;
			}
		}
		
		if started {		
			Some(ans * sign)
		} else {
			None
		}
	}
}

fn read() -> Result<(), Box<dyn Error>> {
	let mut reader = io::BufReader::new(fs::File::open("stdin.txt")?);
	let mut bytes: Vec<u8> = Vec::new();
	reader.read_to_end(&mut bytes)?;
	let mut parser = Parser::new(bytes);

	let n = parser.next().ok_or("N")? as usize;
	let mut v: Vec<i32> = Vec::with_capacity(n);
	let mut empty = 0;
	
	for token in parser {
		if token == -1 {
			empty += 1;
		} else {
			let token = token - 1;
			v.push(token);
		}
	}
	
	Ok(())
}

fn main() {
	let instant = Instant::now();

	if let Err(error) = read() {
		eprintln!("{:?}", error);
	}
   
	println!("{}", instant.elapsed().as_micros() as f64 / 1e6);
}
```

[stdin.txt](https://github.com/EbTech/rust-algorithms/files/4782171/stdin.txt)

</details>

[`.parse()`][parse] is an evil. Handmade solution faster in comparison to C++ with `-O2` using `std::scanf` and reading into an array. 

```
0.171025
0.15101
0.149998
```
<details>
<summary>c++ code</summary>

```c++
#include <iostream>
#include <chrono>

template<typename TimeT = std::chrono::microseconds>
struct measure
{
    template<typename F, typename ...Args>
    static double execution(F&& func, Args&&... args)
    {
        auto start = std::chrono::steady_clock::now();
        std::forward<decltype(func)>(func)(std::forward<Args>(args)...);
        auto duration = std::chrono::duration_cast< TimeT> 
                            (std::chrono::steady_clock::now() - start);
        return double(duration.count()) / 1e6;
    }
};

void solve() {
	std::freopen("stdin", "r", stdin);
	std::freopen("stdout", "w", stdout);
	int n, empty = 0;
	std::scanf("%d", &n);
	int v[size_t(2e5)]{-1};
	for (size_t i = 0, p; i < n; ++i) {
		std::scanf("%d", v + i);
	}
}

int main () {
	std::cerr << measure<>::execution(solve) << std::endl;
}
```

</details>

   [parse]: https://doc.rust-lang.org/nightly/std/primitive.str.html#method.parse

**Comment by EbTech** [comment]
Thanks, that's quite fast!

I like to have a generic `parse()` that applies to a variety of types. On integer types, it redirects to [`from_str_radix()`](https://doc.rust-lang.org/src/core/num/mod.rs.html#5032). Maybe all the checked adds and multiplies are what's slowing it down?

I think contest problems generally can handle the overhead, but traits and macros could be used to defer certain types if you'd like the speed of handcoded implementations. A standard library solution just feels a bit safer to me. Even `UnsafeScanner`'s only assumption is that the input be valid UTF-8, which is true for all programming contests of which I'm aware; in fact, they only use the ASCII subset.

**Comment by koutoftimer** [comment]
I agree that it is better to stay generic, but I almost lost my hope in this approach because of [Problem B][problem-b] on Codeforces.

Writing output is even slower than reading input data. Datastructures like `Vec<i32>`, even made via `::with_capacity` constructor are too much slow..

It took me 8 tried to complete solution. Despite it was good playgroud, I'm still a bit disapointed that Rust with `opt-level=0` is SO SLOW with I\O and all kinds of checks (like overflows for each numeric operation).

What I discovered:
1. Using `std` is pretty much always faster than handmade calculations with `for` loops because of additional checks made for `opt-level=0`.
2. Using `Vec` data structure is slower then regular arrays.

Do you know some tips how to stay generic and do not loose performance on `opt-leve=0` ? IMHO, asking rust community sounds stupid, because they can asnwer something like "we have `opt-level=3` for speed optimized builds" (which is really damn fast).

[problem-b]: https://codeforces.com/gym/102599/submission/84377356

**Comment by EbTech** [comment]
Wow 1000 ms to 78 ms! That's... surprising. I might try this problem in the morning. I thought Codeforces uses opt level 2 with Rust, same as with C++. Were your first tests with O0 as well? I've used Vecs without issue so far, though I haven't run any comparisons of my own...

**Comment by EbTech** [comment]
[Your solution with `UnsafeScanner`](https://codeforces.com/gym/102599/submission/84520378) seems to run fine, taking 62 ms on the judge. The safe version should work too. The [`Vec`-only solution](https://codeforces.com/gym/102599/submission/84521774) did take twice as long and substantially more memory, I'm not sure why.

Btw, I think only users who've solved the problem or enabled coach mode are able to access these Gym links!

**Comment by EbTech** [comment]
Apparently, Codeforces invokes rustc [like this](https://codeforces.com/blog/entry/67391?#comment-521735). `-O` should be the same as optimization level 2.

**Comment by EbTech** [comment]
The example I gave for your Problem B seemed fast enough; do you have a programming contest example where I/O speed was an issue?

**Comment by koutoftimer** [comment]
@EbTech looks like this thread makes no sense because those 1 sec execution time was just a lag.

**Comment by EbTech** [comment]
Sure thing! The benchmarks you provided may be useful later; you might edit your original comment to say which optimization level you used there. Good luck!
