### ISSUE TITLE
Document panics

### ISSUE THREAD

**Issue by NilSet** [EbTech/rust-algorithms#3]
The doc comments should mention potential panics on inputs, such as an out of bounds find or merge on DisjointSets

**Comment by EbTech** [comment]
I added some documentation regarding panics. It's still not perfectly airtight; for example, a client can violate invariants by mutating public members. While a library should properly encapsulate everything, I'm not sure if contest programmers would want that when it's important to be able to hack things up quickly.

**Comment by NilSet** [comment]
I agree that being fully encapsulated is counterproductive here. The panic docs are going to be a good help for knowing what you are hacking on I think.
